"""jwt_auth_channels_videos_comments

Revision ID: 2a22b5a33768
Revises: 
Create Date: 2026-09-10 22:09:44.490135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '2a22b5a33768'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_parent_model',
    sa.Column('str_column', sa.String(length=100), nullable=False),
    sa.Column('int_column', sa.Integer(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('seed_parent_model_pkey'))
    )
    op.create_table('tag_category',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tag_category_pkey'))
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=1024), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key')),
    sa.UniqueConstraint('username', name=op.f('user_username_key'))
    )
    op.create_table('channel',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('avatar', sa.String(length=1024), server_default='', nullable=False),
    sa.Column('banner', sa.String(length=1024), server_default='', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('channel_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('channel_user_id_key'))
    )
    op.create_index(op.f('channel_slug_idx'), 'channel', ['slug'], unique=True)
    op.create_table('playlist',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('playlist_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_pkey'))
    )
    op.create_table('seed_child_model',
    sa.Column('str_column', sa.String(length=100), nullable=False),
    sa.Column('int_column', sa.Integer(), nullable=False),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['seed_parent_model.id'], name=op.f('seed_child_model_parent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('seed_child_model_pkey'))
    )
    op.create_table('video_tag',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tag_category.id'], name=op.f('video_tag_category_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('video_tag_pkey')),
    sa.UniqueConstraint('name', 'category_id', name='uq_video_tag_name_category')
    )
    op.create_table('subscription',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('channel_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('subscription_channel_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('subscription_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_pkey')),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_user_channel_subscription')
    )
    op.create_table('video',
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), server_default='', nullable=False),
    sa.Column('video_file_name', sa.String(length=512), server_default='', nullable=False),
    sa.Column('max_resolution', sa.String(length=50), server_default='1080p', nullable=False),
    sa.Column('views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tags_list', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('channel_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('source_url', sa.String(length=1024), server_default='', nullable=False),
    sa.Column('external_id', sa.String(length=255), server_default='', nullable=False),
    sa.Column('russian_title', sa.String(length=512), server_default='', nullable=False),
    sa.Column('official_title', sa.String(length=512), nullable=True),
    sa.Column('other_titles', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('poster_url', sa.String(length=1024), server_default='', nullable=False),
    sa.Column('is_censored', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('studio', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('translation_types', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dislikes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('video_channel_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('video_pkey')),
    sa.UniqueConstraint('slug', name=op.f('video_slug_key'))
    )
    op.create_index(op.f('video_public_id_idx'), 'video', ['public_id'], unique=True)
    op.create_table('comments',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('video_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dislikes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('comments_parent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('comments_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('comments_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('comments_video_id_idx'), 'comments', ['video_id'], unique=False)
    op.create_table('playlist_video',
    sa.Column('playlist_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('video_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('playlist_video_playlist_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('playlist_video_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_video_pkey')),
    sa.UniqueConstraint('playlist_id', 'video_id', name='uq_playlist_video_playlist_video')
    )
    op.create_table('video_direct_source',
    sa.Column('video_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('quality', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('video_type', sa.String(length=50), server_default='mp4', nullable=False),
    sa.Column('voiceover', sa.String(length=100), server_default='subs', nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('video_direct_source_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('video_direct_source_pkey'))
    )
    op.create_table('video_external_player',
    sa.Column('video_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('embed_url', sa.String(length=2048), nullable=False),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.Column('player_type', sa.String(length=100), server_default='subs', nullable=False),
    sa.Column('voiceover', sa.String(length=100), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('video_external_player_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('video_external_player_pkey'))
    )
    op.create_table('video_likes',
    sa.Column('video_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('is_like', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('video_likes_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('video_likes_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('video_likes_pkey')),
    sa.UniqueConstraint('video_id', 'user_id', name='uq_video_like_user')
    )
    op.create_table('video_tags_association',
    sa.Column('video_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('tag_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['video_tag.id'], name=op.f('video_tags_association_tag_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('video_tags_association_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'tag_id', name=op.f('video_tags_association_pkey'))
    )
    op.create_table('watch_history',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('video_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('progress_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('watch_history_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('watch_history_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('watch_history_pkey')),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_watch_history_user_video')
    )
    op.create_table('comment_likes',
    sa.Column('comment_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('comment_likes_comment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('comment_likes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comment_likes_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes')
    op.drop_table('watch_history')
    op.drop_table('video_tags_association')
    op.drop_table('video_likes')
    op.drop_table('video_external_player')
    op.drop_table('video_direct_source')
    op.drop_table('playlist_video')
    op.drop_index(op.f('comments_video_id_idx'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('video_public_id_idx'), table_name='video')
    op.drop_table('video')
    op.drop_table('subscription')
    op.drop_table('video_tag')
    op.drop_table('seed_child_model')
    op.drop_table('playlist')
    op.drop_index(op.f('channel_slug_idx'), table_name='channel')
    op.drop_table('channel')
    op.drop_table('user')
    op.drop_table('tag_category')
    op.drop_table('seed_parent_model')
    # ### end Alembic commands ###
